
[functions.recommend-mentors]
enabled = true
verify_jwt = true
import_map = "./functions/recommend-mentors/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recommend-mentors/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recommend-mentors/*.html" ]

[functions.recommend-jobs]
enabled = true
verify_jwt = true
import_map = "./functions/recommend-jobs/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recommend-jobs/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recommend-jobs/*.html" ]
